name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tfg-twitter # TODO: update Google Cloud project id
  SERVICE: wtktfg # TODO: update Cloud Run service name
  REGION: europe-southwest1 # TODO: update Cloud Run service region

jobs:
   deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-functions
        pip install google-auth

    - name: Run Python script
      run: python health_check_functions.py '${{ secrets.GCP_JSON }}'

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_JSON }}'

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        # NOTE: If required, update to the appropriate source folder
        source: ./project/
        env_vars: |
          GOOGLE_APPLICATION_CREDENTIALS='${{ secrets.GCP_JSON }}' 

    # If required, use the Cloud Run url output in later steps
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
